### ISSUE TITLE
Elementor

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/modula-lite#316]
Elementor now uses js to make sections full width and we need to find an event to reset our gallery.

**Comment by tanyalp** [comment]
Hi there.  I was suggested to follow this post as I have an issue with my modula galleries not centering suddenly?   I am not sure what these posts do but just wondering if you can help with my issue?  I was told it will be fixed in the next update.  Just wondering also how long that would be?  Do I need to put my old galleries up in the meantime as they don't look good at all now. 

Apologies if I am totally in the wrong place.  Grasping at straws here.  Appreciate any help.
