### ISSUE TITLE
Add a toggle for "powered by"

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#375]
Allow the users to display, on the frontend the "powered by Modula Gallery" link. This should have a toggle and then an input field where users can turn that "powered by" link into their affiliate link. 

Also, I think this ties in with: #290 and we could add a small link in there "earn money with Modula" that links to this settings tab and teaches the users how to sign up for our affiliate program.

**Comment by cristianraiber** [comment]
I also think we could provide a shortcode for this too, so that users could use the shortcode to place the link where they want to on their site. Shortcode could be something like [modula-make-money]

**Comment by giucu91** [comment]
This is partiale done, we need to find a way to implement some aff links.

**Comment by giucu91** [comment]
Here we will make a new tab in Settings that will be named : "Earn Money", here we will have next settings : 
- Aff Link
- "powerd by" text.

Info how to use [modula-make-money] shortcoded. Also the shortcode will have a parameter named text that will overwrite the text setting.

At the end we will output something like "%text% <a href='%aff link%'>Modula</a>";

In the Gallery settings we will have a checkbox in order to enable this powered by under the gallery.
