### ISSUE TITLE
Modula Lite migrating gallery from FooGallery pixels the pictures

### ISSUE THREAD

**Issue by Florin415** [MachoThemes/modula-lite#414]
**Describe the bug**
If we migrate a gallery from FooGallery and we change in Modula the gallery type to Creative Gallery it will pixelate the images 

**To Reproduce**
1. Go to 'FooGallery and make a gallery.'
2. Migrate the gallery to Modula. Before migration deactivate the FooGallery.
3. Make a page and add the migrated gallery to the page.
4. Change the gallery type to Creative Gallery in General ->General settings -> Gallery Type. Update the gallery .
5. Go to the created page and you will see the images have been pixeled ( best use images of people too see the difference).

**Expected behavior**
It should not pixel the migrated images.

**Screenshots**
Screenshot of the issue : 
https://prnt.sc/tdw06x

Screenshot of Modula settings for the gallery : 
https://prnt.sc/tdw0s8

Screenshot of FooGallery settings : 

https://prnt.sc/tdw1dk

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.4.2
* Modula Lite version: master
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
Modula imports the thumbnail size specified by the FooGallery plugin and reflects it in the front. If there are few images in a large container the shown thumbnails will be pixelated because of the image size.

**Comment by razvanaldea89** [comment]
@cristianraiber @giucu91 @andyluak  any thoughts on this one? If we follow what has been placed in FooGallery we get the risk of having pixelated images, but if don't follow ( especially when having multiple galleries with multiple images ) we risk having to modify the migrated galleries one by one so that we can set the thumbnail size.

**Comment by andyluak** [comment]
We could force our thumbnail size when importing galleries with 5 images or less becase of the way FooGallery creates the container to hold the images and we can import the thumbnail size from them when the are over 5 images . On the importer settings page we can add some info as to how we proceed with processing the thumbnails. We can also add a checkbox for the user so that he can override and use out thumbnail size all the time but that would potentially complicate the importer and the user . @giucu91 @cristianraiber @razvanaldea89

**Comment by cristianraiber** [comment]
cc @giucu91 - needs an answer

**Comment by giucu91** [comment]
We will migrate each gallery type from FooGallery like this : 

1. Responsive Image Gallery -> Columns - Automatic - Center
2. Image Viewer -> Slider, if slider extension doesn't exist put it creative.
3. Justified Gallery -> Columns - Automatic - Center
4. Masonry Image Gallery -> Columns
5. Simple Portfolio -> Columns - Automatic - Center
6. Single Thumbnail Gallery -> Columns - Automatic - Center ( If we have modula pro installed Max Images Count will be 1. )

These are the most appropriate gallery types. If the user will change the gallery type he will need to update gallery settings like thumbnail size because we can import a gallery from Foo and make it look ok for all our gallery types.

**Comment by razvanaldea89** [comment]
Also has commit for image size based on new grid types migrated - https://github.com/MachoThemes/modula-lite/commit/74d470637ac5ae989f29a888df471b16dd5d951e
